language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Yasir_Erkam
  username: __token__
  password:
    secure: TORmjd8LPI+viqf9J6xxDeEa0wZuhAE7UnwODr0Ke3sYV2U69NZ0cEi0/EkrNz4OT3il1MVP41rxNnUVzKxNGR6XZpennaB2zHm70tSx5KfUdlCtjXe4PPPUArMM4bGBM1UDWOB5KQOAQFJ7piaYkKt+lXzyniJd6ekhZuXWrUra/AQ+04gp6fKt2Mx/qbaP/RM4n+r6xdnr+zIYSlIcXIF88DWdZF59wA5wkY+qSXlKuxLQ58JkNXYb7YenxbccJCmVL0sTz7FnwbniOGXfOWVRwGaMNYKtmKquFIlwjozrG20B9TFnjT+iir7ZXaVOul/b2Cj2fwE6NWPwkJJMIwGr4sdPk1B2OGR9cSZq58cdj+TSCQCVWGA5YFlN9xZk/ypUcJm64TpuOj2s7PhC2qVmM6zohLpxL9GIdhbWc9AcHVVhFrv2j8hD2R99tHk5lQpbsXKoQbwIguuzIeCmv7XH0rzZycU1J3+q6p6BjFrOUilSPg9N+lF+Kpy7e4tFim9PztOzGmxDiLaJXWcx9xhYSp1TfW+W0mA9kaCnsGkJTxh0y/yWqrCwaBmREQ1Cfy3Nv5zd+UkzmLNuj1aA7gIuwWcrbgC4L0uJHF1JqjoNmt19Fb6+K/AjkUBKBIYZVzBo6KLyF1jRhI0YkY2IJ+J1wdknyuvoSu7OuSsulWQ=
  on:
    tags: true
    repo: yasirerkam/requesturl
    python: 3.9
