language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: ur59lb60H5r2KAP6dinqQNFOxLqtbKhGYpfAM/CCJdHDvu3gjWKbfTwhJei803kqDgWLHoK5ulugbxLLjtdn8dCcE+M8pLpkTbf2DWVVBxbYt/oY6ZfN4vMCIU3h7hvSYDyymGoq8cBHF5pVHxXU1bM/0hBhYo9cbCduI3tEAterGC9vPqiv6AjP4s5QB2NeWBw1CN0OePnvf8I/lPvr5MqSGBAhOqD+Ulg1vUvWGAPkMnP5Op8r2zMrP5kPAIRZM2vcFkjh/TpQGlVZu4jWHxZZA9RsBCJ8q6UEmwokM2dw10Clk3ui+vi4vzQMK6wmsiFPmTtMJuE6UkH+g+SovsVrcPEUSckaVh01vJ1bz2kaxHUjZqR8ekXmpLI72RzrpXa5ZZFjji2pq7d+w1zTfvllM2wEyzGuKeKIRIC6YTIvL2aSDgDYw+PLCokVAcWG3aWeCHZ06r5L/XSxoZj0oZ2zSk62l32g/LEk8xrXeSgSkcnu2di0GLUNpLTmoORQGbMm1So9hJBPDhMre2vZ/bmKhPeIvFuwPX0ddmIjg/o8VrZ17f2wNNqj/qvmSyMXT5X3UaDmMXtVTXe+fKiBfK28C5wFDPG2nJqi73Zh9zmcmHO3I/+2l4mo9gMxjcPmBRJL4NGG4ruxnbeaNUOZDqJSVjHGMtWBwXBtkCqIc1Y=
  on:
    tags: true
    repo: yasirerkam/requesturl
    python: 3.9
